# Generated by Django 3.1 on 2020-12-31 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('time_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
